# Generated by Django 5.0.6 on 2024-06-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_total_order_item_prices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
