# Generated by Django 4.2 on 2024-06-12 18:47

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, default='profile_photos/default_profile_photo.png', upload_to='profile_photos/')),
                ('phone', models.CharField(max_length=40)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('role', models.CharField(choices=[('manager', 'manager'), ('barista', 'barista'), ('waiter', 'waiter'), ('waitress', 'waitress')], default=('manager', 'manager'), max_length=25)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.person')),
            ],
        ),
    ]
