# Generated by Django 4.2 on 2024-06-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='person',
            new_name='person_ptr',
        ),
    ]
